const savedCommutes = {
    morning: [
        { origin: 'Lake Merritt', destination: 'Downtown Berkeley' },
        { origin: '12th St', destination: 'Downtown Berkeley' }
    ],
    evening: [
        { origin: 'Downtown Berkeley', destination: 'Lake Merritt' },
        { origin: 'Downtown Berkeley', destination: '12th St' }
    ]
};

const stationAbrvMap = {
    '12th St. Oakland City Center': '12th',
    '16th St. Mission (SF)': '16th',
    '19th St. Oakland': '19th',
    '24th St. Mission (SF)': '24th',
    'Ashby (Berkeley)': 'ashb',
    'Balboa Park (SF)': 'balb',
    'Bay Fair (San Leandro)': 'bayf',
    'Castro Valley': 'cast',
    'Civic Center (SF)': 'civc',
    Coliseum: 'cols',
    Colma: 'colm',
    Concord: 'conc',
    'Daly City': 'daly',
    'Downtown Berkeley': 'dbrk',
    'Dublin/Pleasanton': 'dubl',
    'El Cerrito del Norte': 'deln',
    'El Cerrito Plaza': 'plza',
    'Embarcadero (SF)': 'embr',
    Fremont: 'frmt',
    'Fruitvale (Oakland)': 'ftvl',
    'Glen Park (SF)': 'glen',
    Hayward: 'hayw',
    Lafayette: 'lafy',
    'Lake Merritt (Oakland)': 'lake',
    'Lake Merritt': 'lake',
    'MacArthur (Oakland)': 'mcar',
    Millbrae: 'mlbr',
    'Montgomery St. (SF)': 'mont',
    'North Berkeley': 'nbrk',
    'North Concord/Martinez': 'ncon',
    "Oakland Int'l Airport": 'oakl',
    Orinda: 'orin',
    'Pittsburg/Bay Point': 'pitt',
    'Pleasant Hill': 'phil',
    'Powell St. (SF)': 'powl',
    Richmond: 'rich',
    'Rockridge (Oakland)': 'rock',
    'San Bruno': 'sbrn',
    "San Francisco Int'l Airport": 'sfia',
    'San Leandro': 'sanl',
    'South Hayward': 'shay',
    'South San Francisco': 'ssan',
    'Union City': 'ucty',
    'Warm Springs/South Fremont': 'warm',
    'Walnut Creek': 'wcrk',
    'West Dublin': 'wdub',
    'West Oakland': 'woak'
};

const stationAbrvList = [
    { abrv: '12th', name: '12th St. Oakland City Center' },
    { abrv: '16th', name: '16th St. Mission (SF)' },
    { abrv: '19th', name: '19th St. Oakland' },
    { abrv: '24th', name: '24th St. Mission (SF)' },
    { abrv: 'ashb', name: 'Ashby (Berkeley)' },
    { abrv: 'balb', name: 'Balboa Park (SF)' },
    { abrv: 'bayf', name: 'Bay Fair (San Leandro)' },
    { abrv: 'cast', name: 'Castro Valley' },
    { abrv: 'civc', name: 'Civic Center (SF)' },
    { abrv: 'cols', name: 'Coliseum' },
    { abrv: 'colm', name: 'Colma' },
    { abrv: 'conc', name: 'Concord' },
    { abrv: 'daly', name: 'Daly City' },
    { abrv: 'dbrk', name: 'Downtown Berkeley' },
    { abrv: 'dubl', name: 'Dublin/Pleasanton' },
    { abrv: 'deln', name: 'El Cerrito del Norte' },
    { abrv: 'plza', name: 'El Cerrito Plaza' },
    { abrv: 'embr', name: 'Embarcadero (SF)' },
    { abrv: 'frmt', name: 'Fremont' },
    { abrv: 'ftvl', name: 'Fruitvale (Oakland)' },
    { abrv: 'glen', name: 'Glen Park (SF)' },
    { abrv: 'hayw', name: 'Hayward' },
    { abrv: 'lafy', name: 'Lafayette' },
    { abrv: 'lake', name: 'Lake Merritt (Oakland)' },
    { abrv: 'mcar', name: 'MacArthur (Oakland)' },
    { abrv: 'mlbr', name: 'Millbrae' },
    { abrv: 'mont', name: 'Montgomery St. (SF)' },
    { abrv: 'nbrk', name: 'North Berkeley' },
    { abrv: 'ncon', name: 'North Concord/Martinez' },
    { abrv: 'oakl', name: "Oakland Int'l Airport" },
    { abrv: 'orin', name: 'Orinda' },
    { abrv: 'pitt', name: 'Pittsburg/Bay Point' },
    { abrv: 'phil', name: 'Pleasant Hill' },
    { abrv: 'powl', name: 'Powell St. (SF)' },
    { abrv: 'rich', name: 'Richmond' },
    { abrv: 'rock', name: 'Rockridge (Oakland)' },
    { abrv: 'sbrn', name: 'San Bruno' },
    { abrv: 'sfia', name: "San Francisco Int'l Airport" },
    { abrv: 'sanl', name: 'San Leandro' },
    { abrv: 'shay', name: 'South Hayward' },
    { abrv: 'ssan', name: 'South San Francisco' },
    { abrv: 'ucty', name: 'Union City' },
    { abrv: 'warm', name: 'Warm Springs/South Fremont' },
    { abrv: 'wcrk', name: 'Walnut Creek' },
    { abrv: 'wdub', name: 'West Dublin' },
    { abrv: 'woak', name: 'West Oakland' }
];

module.exports = {
    stationAbrvMap: stationAbrvMap,
    stationAbrvList: stationAbrvList,
    savedCommutes: savedCommutes
};
